Large rework to enable sending pull requests as user.
The-OpenROAD-Project/actions pull request #10
Opened 2021-06-10 18:52 UTC by mithro

This is done by using two GitHub Apps;
 1) [OpenROAD Pull Request Sender ](https://github.com/organizations/The-OpenROAD-Project-staging/settings/apps/openroad-pull-request-sender) -- The GitHub App which is given permission by a user to actually send pull requests as them and then does the request.
     * It is installed on the `upstream` and `staging` repositories.
     * It needs the ability to modify pull requests.

 2) [OpenROAD Pull Request Sender Auth Check](https://github.com/organizations/The-OpenROAD-Project-private/settings/apps/openroad-pr-sender-auth-check) -- The GitHub App which checks that a user has given the OpenROAD Pull Request Sender the permission to send the pull requests.
     * It is installed on the `private` repositories.
     * It only needs the ability to update check status.

The GitHub Apps run using [Google Cloud Run](https://cloud.google.com/run) (on Google Cloud Platform) under the [`openroad-robot` project](https://console.cloud.google.com/run/detail/us-central1/).

Signed-off-by: Tim 'mithro' Ansell <tansell@google.com>

2021-06-10 23:41 UTC, QuantamHD requested changes

2021-06-10 23:41 UTC, QuantamHD commented on apps/common/db.py
> +        return f"""\
I think these variable names should not be abbreviated.

From the python style guide. 

Function names, variable names, and filenames should be descriptive; eschew abbreviation. In particular, do not use abbreviations that are ambiguous or unfamiliar to readers outside your project, and do not abbreviate by deleting letters within a word.

2021-06-10 23:41 UTC, QuantamHD commented on apps/common/inc.mk
> +	find $(BUILD_DIR) -type d -empty -delete
Should these steps be extracted into a generic target named clean?

2021-06-10 23:41 UTC, QuantamHD commented on apps/common/utils.py
> +    def check(cls, s):
It's not clear to me what this class method is checking I think a one line description would be helpful here. Also renaming s would be helpful as well.

2021-06-10 23:41 UTC, QuantamHD commented on apps/common/utils.py
> +            assert rev , s
If we don't care about the message in the assertion it might just be best to replace s with empty string. I think the s adds confusion.

2021-06-10 23:41 UTC, QuantamHD commented on apps/common/utils.py
> +    def from_json(cls, j):
Adding a comment on what this is extracting would be helpful. As a user I would like to know what I need to provide to this method to get a useful result out. Also rename j to something more representative of the input like user_get_response.

2021-06-10 23:41 UTC, QuantamHD commented on apps/common/utils.py
> +        assert '@' in s, s
These asserts should have a more helpful error message rather than just the input.

2021-06-10 23:41 UTC, QuantamHD commented on apps/common/utils.py
> +        pr, rev  = rest.split('@', maxsplit=1)
Adding context to the variable names would be helpful. What is pr in this case? Is it the url, an ID, or some object representing a PR.

2021-06-10 23:41 UTC, QuantamHD commented on apps/pull-request-sender-auth-check/app.py
> +        if c['id'] in (2688818725,):
Magic numbers should have a comment explaining where they came from. Ideally this would be a global variable of some kind.

2021-06-10 23:41 UTC, QuantamHD commented on apps/pull-request-sender-auth-check/app.py
> +    t = db.Token.latest(info.user)
Rename t latest_token.

2021-06-10 23:41 UTC, QuantamHD commented on apps/pull-request-sender-auth-check/app.py
> +def auth_check_on_private_pr(info):
This method seems to be doing a lot. Giving a one line description with a few sentences underneath to explain intent would help with readability.

2021-06-10 23:41 UTC, QuantamHD commented on apps/pull-request-sender/app.py
> +    t = db.Token.latest(user)
Renamed latest_token

2021-06-10 23:41 UTC, QuantamHD commented on apps/upstream-sync/app.py
> +        if now - cls._cache_updated > 60*5:
This number needs to document what units it is in.

2021-11-29 16:50 UTC, maliberty commented
@mithro is this PR still relevant?

2021-11-29 17:16 UTC, mithro commented
Yes. This makes the pull requests come from the original user rather than the bot. 

However, I don't recall what the state here was or why it wasn't merged.

2021-11-29 17:18 UTC, maliberty commented
I see a number of comments from @QuantamHD that need addressing.

I agree the goal is still relevant.

2026-05-27 20:34 UTC, closed without merging